[package]
name = "blumbot"
version = "0.1.0"
edition = "2021"

[dependencies]
mouse-rs = "0.4.2"
screenshots = "0.8.10"
colored = "3.0.0"
winapi = { version = "0.3.9", features = ["winuser", "windef", "minwindef"] }

